### ISSUE TITLE
Similar projects

### ISSUE THREAD

**Issue by daurnimator** [cloudflare/lua-aho-corasick#6]
How does this compare to https://github.com/chatid/lua-ahocorasick ?

**Comment by yangshuxin** [comment]
I managed to compile  (https://github.com/chatid/lua-ahocorasick) by making several changes:
   - it seems this work depends on multifast-v1.4.2 instead of multifast-v1.0.0
   - it need to generated *.so instead of *.a (both for the https://github.com/chatid/lua-ahocorasick and multifast).
   - and bunch of minor changes (including the opt-level, set to -O3).

 Compared against brute-force string.find(), we have following result.  (column-1 is the # of string in the pattern-set, column 2 is the time corresponding to brute-force string.match, 3rd column corresponds to chatid's, and last column is out implementation). The luajit used for this benchmark is luajit v2.1.

--------------------------------------------------------
#str-in-dict string.find  chatid's  cloudflare's
35           0.267644     1.111072  0.101049
2            0.010902     0.546165  0.064553
144          1.731733     1.435951  0.148882
13           0.088519     0.677722  0.084606
56           0.470575     1.297198  0.11482
45           0.506767     0.865649  0.068665
10           0.096066     0.747365  0.067169
41           0.457636     0.789964  0.06708
-------------------------------------------------------

Thanks

**Comment by daurnimator** [comment]
Thanks for the comparison!

Do you have the sample program you used to perform the benchmark?
As the chatid library is just bindings to multifast, I assume this result means that multifast itself is not as fast as cloudflare's C lib?

**Comment by yangshuxin** [comment]
>Do you have the sample program you used to perform the benchmark?

We do. Unfortunately, we cannot share this script as it's hard-coded with some customer data (including its format etc).  This is the script we used for "benchmarking" by comparing performance side-by-side with other implementation. I did manually compare performance against some implementations available on the Internet, and believe the performance of our implementation is not bad. So from then on, we only focus on tuning the performance of our implementation. The "make benchmark" is for that purpose. 

  That being said, I think it is good idea to write a script comparing performance side-by-side with other implementation. It will help us to pin-point where we lack behind or are better than others.

>  I assume this result means that multifast itself is not as fast as cloudflare's C lib?
It could. Another reasons would the lua-code itself. It use Lua API instead of FFI. The former has higher call-overhead. For the C-land code, the performance bottle-neck is in making state transition. We try hard to reduce time in state transition. For instance, we pack all possible transition inputs in an array, and use binary-search to find the corresponding next-state; we also use linear search if the outcome number is quite small; we carefully layout and restructure the code to avoid/reduce branches...

**Comment by daurnimator** [comment]
> > I assume this result means that multifast itself is not as fast as cloudflare's C lib?
>
> It could. Another reasons would the lua-code itself. It use Lua API instead of FFI. 

Interesting thought.

Any chance you could compare it without lua? i.e. using C apis only?
(or compare by making ffi bindings to multifast, but that's probably more effort).

**Comment by yangshuxin** [comment]
Our lua layer (i call it adapter) is pretty thin, it does nothing but pass parameter to C function via FFI. We did compare the performance before, I did not see any performance difference w/ or wo/ the adapter no matter with luajit 2.0 or luajit 2.1. (PS: luajit 2.1 seems to be much better than luajit 2.0, in another project https://github.com/cloudflare/lua-resty-json, we do see big difference between them. in that project, the lua adapter is not paper-thin)

**Comment by daurnimator** [comment]
> Our lua layer (i call it adapter) is pretty thin, it does nothing but pass parameter to C function via FFI.

I meant to rule out the 'thickness' of the chatid multifast bindings: compare C program to C program so that we know if the multifast library is slow, or the problem is in the bindings

**Comment by agentzh** [comment]
@daurnimator Well, you can also use profiling tools like flame graphs to check the CPU time distribution :)

**Comment by daurnimator** [comment]
> @daurnimator Well, you can also use profiling tools like flame graphs to check the CPU time distribution :)

Indeed you could! Just I do not have a good test data sample, and @yangshuxin said above he is unable to share his; hence I must request he completes this for me.

**Comment by yangshuxin** [comment]
@daurnimator, I didn't know the multifast before, the data I present to you is provided by modifying a existing old script to collect the data for you. For now, we are not very interested in multifast. we might be interested in it in the future, and dig into its internal. If you are interested in multifast, you may drop a line to the author, I believe they can answer your questions precisely. 

Anyway, I appreciate you bringing multifast to our attention.
