### ISSUE TITLE
about load_ac.lua

### ISSUE THREAD

**Issue by hy05190134** [cloudflare/lua-aho-corasick#8]
when I use load_ac.lua in macos, sometimes it will report and generate core file
malloc: *** error for object 0x7f8bbc831400: incorrect checksum for freed object - object was probably modified after being freed

**Comment by hy05190134** [comment]
I add "local ac_free = nil"  below "local ac_match = nil"

**Comment by hy05190134** [comment]
how to find the problem in macos?

**Comment by yangshuxin** [comment]
Your change is correct, I don't think the problem has something to do with that change. 

It looks like a double-free problem.  As far as I can guess, you might call ac_free() explictly, and later on GC get rid of the AC instance, and call ac_free() again, giving rise to the double-free problem.

To pin-point the problem, you can:
   
o. call collectgarbage() in your lua-script aggressively
o. figure out where the crash take place. I guess it's very likely take place in ac_free().
o. I'm more than happy to help, so long as I can reproduce your environement.

**Comment by hy05190134** [comment]
local ac = require "libac"
local _ac_dicts = {}
local haystack = {"aab", "ccd", "ddd"}
local match, _ac                                                                                          
if (not _ac_dicts[id]) then                                                                               
      _ac = ac.create_ac(haystack)                                                                          
       _ac_dicts[id] = _ac                                                                                   
 else                                                                                                      
       _log(self, "AC dict found, pulling from the module cache")                                            
       _ac = _ac_dicts[id]                                                                                   
 end                                                                                                       
 match = ac.match(_ac, "aabfdfdfdf")                                                              
  
as far as you know, is there a problem if I don't put "local ac_free = nil below local ac_match = nil" in load_ac.lua, where should I put collectgarbage("count") in the code above, thanks

**Comment by hy05190134** [comment]
I put ac to lua table element, is there a problem when table gargage?

**Comment by yangshuxin** [comment]
> about the pseudo Lua code

I don't see any problem. You can save the ac instance anywhere you like.

>as far as you know, is there a problem if I don't put "local ac_free = nil below local ac_match = nil" in load_ac.lua, 

I don't see problem either. Actually, last night I wrote a Lua snippet (simlar to the pseudo-code you illustrated) along with the change you made to the load_ac.lua, and ran it on OSX 10.8 with luajit 2.1. I didn't see problem.

>where should I put collectgarbage("count") in the code above, thanks

I didn't mean collectgarbage("count") in my previous reponse, I meant collectgarbage().  The purpose to call collectgarbage() is to collect gargae ASAP, such that you can *consistently* expose the problem.  If the GC is called lazily, you are likely come across a situation where the code sometime works and sometimes does not. I added bunch of collectgarbage() in tests/load_ac_test.lua, which once exposed bunch of problems.  Of course, the collectgarbage() is for debugging purpose, do not add them to the production code. 

Maybe you can add the collectgargate() right before the ac.match(ac, "/the/string") statement.

Could you please answer following questions:
 1) Are you sure the problem arise when ac_free() is called?.  If this is the case, you can add some fprintf to the ac_match() ac_free() C functions the print the pointer of the instance, which would give you some hint as to where the problem take place. 

 2) change the Makefile, adding '-g -DVERIFY' to the CFLAGS.  When -DVERIFY is turned on, assertion is turned on, and internal state is verified.

 3) If it is possible, could you please attach a minimal real lua code (instead of the pseudo code).

Thanks!

**Comment by hy05190134** [comment]
thanks for so detailed answering, I will try according to your advice. By the way, another problem, how can I modify to match vaguely not accurately, that is to say,  like using pcre's find rather than just equal string. Now I am using load_ac.lua requirement.

**Comment by hy05190134** [comment]
is there a problem when I use in recursive run？

-- uses CF implementation of aho-corasick-lua
local function _ac_lookup(self, collection, haystack, id)
    local match, _ac

    -- dictionary creation is expensive, so we use the id of the rule as the key to cache the created dictionary
    if (not _ac_dicts[id]) then
        _log(self, "AC dict not found, calling libac.so")
        _ac = ac.create_ac(haystack)
        _ac_dicts[id] = _ac
    else
        _log(self, "AC dict found, pulling from the module cache")
        _ac = _ac_dicts[id]
    end

    if (type(collection) == "table") then
        for _, v in ipairs(collection) do
            match = _ac_lookup(self, v, haystack, id)
            if (match) then
                break
            end
        end
    else
        match = ac.match(_ac, collection)
    end

    return match
end

**Comment by hy05190134** [comment]
when I add collect garbage() the problem is occurred  every time, is it right to show the gc is called lazily which affect the code run successfully, maybe recursive execution is the real problem?

**Comment by hy05190134** [comment]
process(92298,0x7fff70370300) malloc: *** error for object 0x7fdc73802a00:  

can you explain what's the two pointer indict? if I put fprintf in c code, then the pointer will be the same with the later?

**Comment by hy05190134** [comment]
the core is generated Not every time but the ability is more than not add "collect garbage()"

**Comment by hy05190134** [comment]
I  print the sequence for ac_free and ac_create , and I find that I just put a local var to global var, maybe that's the real problem.

**Comment by hy05190134** [comment]
![screen shot 2015-05-26 at 8 36 34 pm](https://cloud.githubusercontent.com/assets/7495796/7812655/efc40d7c-03e6-11e5-9b44-166fb16eb4bf.JPEG)

**Comment by yangshuxin** [comment]
I ask people around, nobody can figure out what may go wrong:-(

o. Is it double free problem?
   It's really unlikely, as the CDATA objects are deleted by GC. On the other hand, the runtime error-message for double-free is something like "error for object xxxx: pointer being freed was not allocated", which is different from the one you got. Could you please run your code in gdb/lldb, and set breakpoint at malloc_error_break() to see where the problem take place?
 
   It seems you are running luajit inside Nginx. To ease debugging, you can add following directives to the nginx.conf so that Nginx will not fork many sub-process:

{code}
daemon off;
master_process off;
{code}

2. valgrind could come in handy.

   Yes, valgrind could pin-point the nature of the problem. But you need to patch Valgrind in order to run  with nginx + luajit (Valgrind work with nginx, and conflict with luajit due to memory allocation issue).  You can find the patch here: https://gist.github.com/calio/c049758d1de0b8c4336e

3. modify load_ac.lua.

  3.1) restore the load_ac.lua back to the pristine state. and modify the statement ffi.gc(ac, ac_free)" to "ffi.gc(ac, ac_lib.ac_free) to see if the problem disappear.
   
 3.2) restore the load_ac.lua back to the pristine state, then a whatever global varable in the module to see if the problem magically disappear:-)

 3.3) restore the load_ac.lua back to the pristine state, introduce the global variable pointing ac_create() or ac_match() to see if the problem magically disappear:-)

Thanks

**Comment by hy05190134** [comment]
![screen shot 2015-05-26 at 8 36 34 pm](https://cloud.githubusercontent.com/assets/7495796/7827434/d5324096-0459-11e5-9c4c-194a2cc9c210.JPEG)

**Comment by hy05190134** [comment]
![screen shot 2015-05-27 at 9 54 15 am](https://cloud.githubusercontent.com/assets/7495796/7827437/e1a327a0-0459-11e5-8f28-7c9b9d038251.JPEG)

**Comment by hy05190134** [comment]
we really use nginx+ lua + luajit to run the code

**Comment by hy05190134** [comment]
![screen shot 2015-05-27 at 11 20 27 am](https://cloud.githubusercontent.com/assets/7495796/7828165/6d8eec10-0462-11e5-87e1-7f5b0b72d3f8.JPEG)

**Comment by yangshuxin** [comment]
Hi,

   Let us diagnose the weird problem offline. I will drop a line to your 
email account you put on https://github.com/hy05190134.

Thanks
Shuxin

**Comment by yangshuxin** [comment]
It does not seem to be the problem of AC. The crash takes place when nginx destroy a memory pool, and AC does not use Nginx's mempool at all.

On Linux side, our testing using Valgrind does not find any illegal read/write.  I don't find illegal read/write oldish OSX either. That being said, I don't rule out potential problem on the most recent OSX.

However, since we don't have the environment to reproduce the problem, we are not able to provide more assistant. I would close this issue for now. I would be more than happy to help if the bug-reporter make some progress at his side.
